AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - '_site/**/*'
    - '.jekyll-cache/**/*'
    - 'node_modules/**/*'

# Layout
Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '_plugins/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - '_plugins/**/*'

Metrics/AbcSize:
  Exclude:
    - '_plugins/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - '_plugins/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - '_plugins/**/*'

# Lint
Lint/MissingSuper:
  Exclude:
    - '_plugins/**/*'

# Naming
Naming/FileName:
  Exclude:
    - 'Gemfile'

# Gemspec
Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

# Style
Style/GuardClause:
  Exclude:
    - '_plugins/**/*'

